platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
xcodeproj '../Coro.xcodeproj'

target "Coro" do
    pod 'Alamofire', '~> 1.2'
    pod 'SwiftyJSON', '~> 2.2.0'
end